name = "fxlocus-system"
main = ".open-next/worker.js"
compatibility_date = "2026-02-05"
compatibility_flags = ["nodejs_compat"]

[vars]
APP_BASE_URL = "https://fangzhenxunlian.com"
SYSTEM_COOKIE_DOMAIN = ""
D1_NAME = "fxlocus-system"
R2_BUCKET = "fxlocus-system-files"
R2_ENDPOINT = "https://5cc7fa12a1d8efb9c4b0438581774a88.r2.cloudflarestorage.com"
R2_PUBLIC_BASE_URL = "https://fangzhenxunlian.com"
R2_CDN_BASE_URL = "https://fangzhenxunlian.com"
NEXT_PUBLIC_R2_CDN_BASE_URL = "https://fangzhenxunlian.com"
SYSTEM_FILES_BUCKET = "fxlocus-system-files"
SYSTEM_CLASSIC_TRADES_BUCKET = "fxlocus-system-files"
SYSTEM_WEEKLY_SUMMARIES_BUCKET = "fxlocus-system-files"
SYSTEM_SUMMARY_IMAGES_BUCKET = "fxlocus-system-files"
SYSTEM_CONSULT_BUCKET = "fxlocus-system-files"
R2_DESKTOP_PREFIX = "desktop"
R2_MOBILE_PREFIX = "mobile"
NEXT_PUBLIC_APP_VERSION = "0.1.0"
NEXT_PUBLIC_LADDER_REFRESH_MS = "60000"
NEXT_PUBLIC_WEBRTC_TURN_URLS = ""
NEXT_PUBLIC_WEBRTC_TURN_USERNAME = ""
NEXT_PUBLIC_WEBRTC_TURN_CREDENTIAL = ""
LOGIN_RATE_LIMIT_STORE = "d1"
MIDDLEWARE_LOGIN_RATE_WINDOW_MS = "60000"
MIDDLEWARE_LOGIN_RATE_LIMIT_PER_IP = "80"
LOGIN_RATE_LIMIT_WINDOW_MS = "600000"
LOGIN_RATE_LIMIT_MAX_ATTEMPTS_IP = "60"
LOGIN_RATE_LIMIT_MAX_ATTEMPTS_EMAIL = "10"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "MY_DB"
database_name = "fxlocus-system"
database_id = "bea0711c-c8e7-4709-9563-35485e17c22e"

[[r2_buckets]]
binding = "R2_ASSETS"
bucket_name = "fxlocus-system-files"
